# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: false
  branches:
    include:
    - master

# Enable PR triggers that target the master branch
pr:
  autoCancel: true # cancel previous builds on push
  branches:
    include:
    - master

strategy:
  # Limit number of executors used so other pipelines can run too
  maxParallel: 10
  matrix:
    # ---- ghc-flavor : ghc-8.10.1
    # ghc-8.4 is no longer supported for bootstrapping as of
    # https://gitlab.haskell.org/ghc/ghc/commit/24620182abdfcc65a0cfc0e2f3bc391d464d0ad5
    # 09/29/2019. Subsequent removal of CPP guards in
    # https://gitlab.haskell.org/ghc/ghc/commit/795986aaf33e2ffc233836b86a92a77366c91db2
    # for 'InfoTable.hsc' break the compile.

    # -- compiler : ghc-8.8.1

    # ---- ghc-flavor : da-ghc-8.8.1
    linux-da-ghc-881-881:
      image: "Ubuntu 16.04"
      ghc-flavor: "da-ghc-8.8.1"
      resolver: "nightly-2019-09-26"
    windows-da-ghc-881-881:
      image: "vs2017-win2016"
      ghc-flavor: "da-ghc-8.8.1"
      resolver: "nightly-2019-09-26"
    mac-da-ghc-881-881:
      image: "macOS-10.14"
      ghc-flavor: "da-ghc-8.8.1"
      resolver: "nightly-2019-09-26"

    # -- compiler : ghc-8.8.3

    # ---- ghc-flavor : ghc-8.8.3
    linux-ghc-883-883:
      image: "Ubuntu 16.04"
      ghc-flavor: "ghc-8.8.3"
      resolver: "nightly-2020-03-14"
    # windows-ghc-883-883:
    #   image: "vs2017-win2016"
    #   ghc-flavor: "ghc-8.8.3"
    #   resolver: "nightly-2020-03-14"
    mac-ghc-883-883:
      image: "macOS-10.14"
      ghc-flavor: "ghc-8.8.3"
      resolver: "nightly-2020-03-14"
    # ---- ghc-flavor : ghc-8.10.1
    linux-ghc-8101-883:
      image: "Ubuntu 16.04"
      ghc-flavor: "ghc-8.10.1"
      resolver: "nightly-2020-03-14"
    mac-ghc-8101-883:
      image: "macOS-10.14"
      ghc-flavor: "ghc-8.10.1"
      resolver: "nightly-2020-03-14"
    # windows-ghc-8101-883:
    #   image: "vs2017-win2016"
    #   ghc-flavor: "ghc-8.10.1"
    #   resolver: "nightly-2020-03-14"
    # ---- ghc-flavor : ghc-master
    linux-ghc-master-883:
      image: "Ubuntu 16.04"
      ghc-flavor: "ghc-master"
      resolver: "nightly-2020-03-14"
    # windows-ghc-master-883:
    #   image: "vs2017-win2016"
    #   ghc-flavor: "ghc-master"
    #   resolver: "nightly-2020-03-14"
    mac-ghc-master-883:
      image: "macOS-10.14"
      ghc-flavor: "ghc-master"
      resolver: "nightly-2020-03-14"


pool: {vmImage: '$(image)'}

steps:
  # macOS
  - bash: |
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      brew install automake
      brew upgrade gmp
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: Install brew

  - script: |
      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s CI.hs
      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s examples/mini-hlint/src
      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s examples/mini-compile/src
      curl -sSL https://get.haskellstack.org/ | sh
      stack --resolver $(resolver) setup > /dev/null
      stack runhaskell --resolver $(resolver) --package extra --package optparse-applicative -- CI.hs --ghc-flavor $(ghc-flavor) --resolver $(resolver)
